all_recipes_in_game = [{'name': 'cuba libre',
                        'price': 28,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'cola', 'amount': 12},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'passionfruit mojito',
                        'price': 29,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 5},
                                            'ing2': {'name': 'passionfruit juice', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 3},
                                            'ing4': {'name': 'sugar syrup', 'amount': 2},
                                            'ing5': {'name': 'soda water', 'amount': 2},
                                            'ing6': {'name': 'mint', 'amount': 2},
                                            'ing7': {'name': 'ice', 'amount': 2}}},
                        {'name': 'daiquiri',
                        'price': 30,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 10},
                                            'ing2': {'name': 'lime juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 4}}},
                        {'name': 'screwdriver',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 12},
                                            'ing3': {'name': 'ice', 'amount': 2}}},
                        {'name': 'gin & tonic',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'tonic water', 'amount': 10},
                                            'ing3': {'name': 'lime', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'french 75',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'lemon juice', 'amount': 4},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2},
                                            'ing4': {'name': 'champagne', 'amount': 8}}},
                        {'name': 'mojito',
                        'price': 33,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'lime juice', 'amount': 3},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2},
                                            'ing4': {'name': 'soda water', 'amount': 5},
                                            'ing5': {'name': 'mint', 'amount': 2},
                                            'ing6': {'name': 'ice', 'amount': 2}}},
                        {'name': 'mango daiquiri',
                        'price': 37,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 8},
                                            'ing2': {'name': 'mango juice', 'amount': 7},
                                            'ing3': {'name': 'lime juice', 'amount': 3},
                                            'ing4': {'name': 'sugar syrup', 'amount': 2}}},
                        {'name': 'piña colada',
                        'price': 40,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'pineapple juice', 'amount': 8},
                                            'ing3': {'name': 'coconut cream', 'amount': 4},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'gimlet',
                        'price': 44,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 12},
                                            'ing2': {'name': 'lime juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2}}},
                        {'name': 'sex on the beach',
                        'price': 49,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'cranberry juice', 'amount': 5},
                                            'ing3': {'name': 'orange juice', 'amount': 7},
                                            'ing4': {'name': 'grenadine', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'tequila sunrise',
                        'price': 52,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 10},
                                            'ing3': {'name': 'grenadine', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'long island iced tea',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 2},
                                            'ing2': {'name': 'gin', 'amount': 2},
                                            'ing3': {'name': 'white rum', 'amount': 2},
                                            'ing4': {'name': 'tequila', 'amount': 2},
                                            'ing5': {'name': 'triple sec', 'amount': 2},
                                            'ing6': {'name': 'lemon juice', 'amount': 3},
                                            'ing7': {'name': 'cola', 'amount': 5},
                                            'ing8': {'name': 'ice', 'amount': 2}}},
                        {'name': 'apple mule',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'apple juice', 'amount': 6},
                                            'ing3': {'name': 'ginger beer', 'amount': 6},
                                            'ing4': {'name': 'lime juice', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'tropical sunrise',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 6},
                                            'ing2': {'name': 'mango juice', 'amount': 7},
                                            'ing3': {'name': 'passionfruit juice', 'amount': 3},
                                            'ing4': {'name': 'grenadine', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'porn star martini',
                        'price': 66,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'amaretto', 'amount': 3},
                                            'ing3': {'name': 'pineapple juice', 'amount': 5},
                                            'ing4': {'name': 'lime juice', 'amount': 2},
                                            'ing5': {'name': 'champagne', 'amount': 2}}},
                        {'name': 'cosmopolitan',
                        'price': 68,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'triple sec', 'amount': 4},
                                            'ing3': {'name': 'cranberry juice', 'amount': 6},
                                            'ing4': {'name': 'lime juice', 'amount': 2}}},
                        {'name': 'moscow mule',
                        'price': 74,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'ginger beer', 'amount': 10},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'elderflower collins',
                        'price': 86,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'elderflower liqueur', 'amount': 4},
                                            'ing3': {'name': 'lemon juice', 'amount': 4},
                                            'ing4': {'name': 'soda water', 'amount': 4},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'corpse reviver',
                        'price': 94,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 7},
                                            'ing2': {'name': 'triple sec', 'amount': 6},
                                            'ing3': {'name': 'absinthe', 'amount': 1},
                                            'ing4': {'name': 'lemon juice', 'amount': 6}}},
                        {'name': 'blue lagoon',
                        'price': 96,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'blue curaçao', 'amount': 4},
                                            'ing3': {'name': 'lemon juice', 'amount': 2},
                                            'ing4': {'name': 'soda water', 'amount': 6},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'dark & stormy',
                        'price': 102,
                        'makingprocess': {'ing1': {'name': 'dark rum', 'amount': 7},
                                            'ing2': {'name': 'ginger beer', 'amount': 9},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'margarita',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 10},
                                            'ing2': {'name': 'triple sec', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'whiskey sour',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'whiskey', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'amaretto sour',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'amaretto', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'white russian',
                        'price': 110,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'kahlúa', 'amount': 6},
                                            'ing3': {'name': 'cream', 'amount': 4},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'peach fizz',
                        'price': 110,
                        'makingprocess': {'ing1': {'name': 'peach schnapps', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 7},
                                            'ing3': {'name': 'soda water', 'amount': 6},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'death in the afternoon',
                        'price': 116,
                        'makingprocess': {'ing1': {'name': 'absinthe', 'amount': 4}, 'ing2': {'name': 'champagne', 'amount': 16}}},
                        {'name': 'dry martini',
                        'price': 124,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 16}, 'ing2': {'name': 'dry vermouth', 'amount': 4}}},
                        {'name': 'green demon',
                        'price': 127,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 5},
                                            'ing2': {'name': 'vodka', 'amount': 5},
                                            'ing3': {'name': 'pineapple juice', 'amount': 8},
                                            'ing4': {'name': 'blue curaçao', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'espresso martini',
                        'price': 129,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 9},
                                            'ing2': {'name': 'kahlúa', 'amount': 8},
                                            'ing3': {'name': 'cream', 'amount': 3}}},
                        {'name': 'blue margarita',
                        'price': 134,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 10},
                                            'ing2': {'name': 'blue curaçao', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'midori sour',
                        'price': 178,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'hugo spritz',
                        'price': 178,
                        'makingprocess': {'ing1': {'name': 'elderflower liqueur', 'amount': 4},
                                            'ing2': {'name': 'prosecco', 'amount': 10},
                                            'ing3': {'name': 'soda water', 'amount': 3},
                                            'ing4': {'name': 'mint', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'japanese slipper',
                        'price': 192,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 8},
                                            'ing2': {'name': 'triple sec', 'amount': 8},
                                            'ing3': {'name': 'lemon juice', 'amount': 4}}},
                        {'name': 'bellini prosecco',
                        'price': 204,
                        'makingprocess': {'ing1': {'name': 'prosecco', 'amount': 14}, 'ing2': {'name': 'peach juice', 'amount': 6}}},
                        {'name': 'peach bellini royale',
                        'price': 206,
                        'makingprocess': {'ing1': {'name': 'peach schnapps', 'amount': 4},
                                            'ing2': {'name': 'peach juice', 'amount': 6},
                                            'ing3': {'name': 'prosecco', 'amount': 10}}},
                        {'name': 'negroni',
                        'price': 228,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 7},
                                            'ing2': {'name': 'campari', 'amount': 7},
                                            'ing3': {'name': 'sweet vermouth', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'americano',
                        'price': 234,
                        'makingprocess': {'ing1': {'name': 'campari', 'amount': 7},
                                            'ing2': {'name': 'sweet vermouth', 'amount': 7},
                                            'ing3': {'name': 'soda water', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'manhattan',
                        'price': 238,
                        'makingprocess': {'ing1': {'name': 'whiskey', 'amount': 12},
                                            'ing2': {'name': 'sweet vermouth', 'amount': 6},
                                            'ing3': {'name': 'bitters', 'amount': 2}}}
]