from main import ingredient_icons_list, glass_tags_list, glasses_list

all_recipes_in_game = [{'name': 'cuba libre',
                        'price': 28,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'cola', 'amount': 12},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'passionfruit mojito',
                        'price': 29,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 5},
                                            'ing2': {'name': 'passionfruit juice', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 3},
                                            'ing4': {'name': 'sugar syrup', 'amount': 2},
                                            'ing5': {'name': 'soda water', 'amount': 2},
                                            'ing6': {'name': 'mint', 'amount': 2},
                                            'ing7': {'name': 'ice', 'amount': 2}}},
                        {'name': 'daiquiri',
                        'price': 30,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 10},
                                            'ing2': {'name': 'lime juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 4}}},
                        {'name': 'screwdriver',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 12},
                                            'ing3': {'name': 'ice', 'amount': 2}}},
                        {'name': 'gin & tonic',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'tonic water', 'amount': 10},
                                            'ing3': {'name': 'lime', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'french 75',
                        'price': 32,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'lemon juice', 'amount': 4},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2},
                                            'ing4': {'name': 'champagne', 'amount': 8}}},
                        {'name': 'mojito',
                        'price': 33,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'lime juice', 'amount': 3},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2},
                                            'ing4': {'name': 'soda water', 'amount': 5},
                                            'ing5': {'name': 'mint', 'amount': 2},
                                            'ing6': {'name': 'ice', 'amount': 2}}},
                        {'name': 'mango daiquiri',
                        'price': 37,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 8},
                                            'ing2': {'name': 'mango juice', 'amount': 7},
                                            'ing3': {'name': 'lime juice', 'amount': 3},
                                            'ing4': {'name': 'sugar syrup', 'amount': 2}}},
                        {'name': 'piña colada',
                        'price': 40,
                        'makingprocess': {'ing1': {'name': 'white rum', 'amount': 6},
                                            'ing2': {'name': 'pineapple juice', 'amount': 8},
                                            'ing3': {'name': 'coconut cream', 'amount': 4},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'gimlet',
                        'price': 44,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 12},
                                            'ing2': {'name': 'lime juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 2}}},
                        {'name': 'sex on the beach',
                        'price': 49,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'cranberry juice', 'amount': 5},
                                            'ing3': {'name': 'orange juice', 'amount': 7},
                                            'ing4': {'name': 'grenadine', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'tequila sunrise',
                        'price': 52,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 10},
                                            'ing3': {'name': 'grenadine', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'long island iced tea',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 2},
                                            'ing2': {'name': 'gin', 'amount': 2},
                                            'ing3': {'name': 'white rum', 'amount': 2},
                                            'ing4': {'name': 'tequila', 'amount': 2},
                                            'ing5': {'name': 'triple sec', 'amount': 2},
                                            'ing6': {'name': 'lemon juice', 'amount': 3},
                                            'ing7': {'name': 'cola', 'amount': 5},
                                            'ing8': {'name': 'ice', 'amount': 2}}},
                        {'name': 'apple mule',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'apple juice', 'amount': 6},
                                            'ing3': {'name': 'ginger beer', 'amount': 6},
                                            'ing4': {'name': 'lime juice', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'tropical sunrise',
                        'price': 62,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 6},
                                            'ing2': {'name': 'mango juice', 'amount': 7},
                                            'ing3': {'name': 'passionfruit juice', 'amount': 3},
                                            'ing4': {'name': 'grenadine', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'porn star martini',
                        'price': 66,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'amaretto', 'amount': 3},
                                            'ing3': {'name': 'pineapple juice', 'amount': 5},
                                            'ing4': {'name': 'lime juice', 'amount': 2},
                                            'ing5': {'name': 'champagne', 'amount': 2}}},
                        {'name': 'cosmopolitan',
                        'price': 68,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'triple sec', 'amount': 4},
                                            'ing3': {'name': 'cranberry juice', 'amount': 6},
                                            'ing4': {'name': 'lime juice', 'amount': 2}}},
                        {'name': 'moscow mule',
                        'price': 74,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'ginger beer', 'amount': 10},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'elderflower collins',
                        'price': 86,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 6},
                                            'ing2': {'name': 'elderflower liqueur', 'amount': 4},
                                            'ing3': {'name': 'lemon juice', 'amount': 4},
                                            'ing4': {'name': 'soda water', 'amount': 4},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'corpse reviver',
                        'price': 94,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 7},
                                            'ing2': {'name': 'triple sec', 'amount': 6},
                                            'ing3': {'name': 'absinthe', 'amount': 1},
                                            'ing4': {'name': 'lemon juice', 'amount': 6}}},
                        {'name': 'blue lagoon',
                        'price': 96,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 6},
                                            'ing2': {'name': 'blue curaçao', 'amount': 4},
                                            'ing3': {'name': 'lemon juice', 'amount': 2},
                                            'ing4': {'name': 'soda water', 'amount': 6},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'dark & stormy',
                        'price': 102,
                        'makingprocess': {'ing1': {'name': 'dark rum', 'amount': 7},
                                            'ing2': {'name': 'ginger beer', 'amount': 9},
                                            'ing3': {'name': 'lime juice', 'amount': 2},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'margarita',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 10},
                                            'ing2': {'name': 'triple sec', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'whiskey sour',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'whiskey', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'amaretto sour',
                        'price': 106,
                        'makingprocess': {'ing1': {'name': 'amaretto', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'white russian',
                        'price': 110,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 8},
                                            'ing2': {'name': 'kahlúa', 'amount': 6},
                                            'ing3': {'name': 'cream', 'amount': 4},
                                            'ing4': {'name': 'ice', 'amount': 2}}},
                        {'name': 'peach fizz',
                        'price': 110,
                        'makingprocess': {'ing1': {'name': 'peach schnapps', 'amount': 6},
                                            'ing2': {'name': 'orange juice', 'amount': 7},
                                            'ing3': {'name': 'soda water', 'amount': 6},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'death in the afternoon',
                        'price': 116,
                        'makingprocess': {'ing1': {'name': 'absinthe', 'amount': 4}, 'ing2': {'name': 'champagne', 'amount': 16}}},
                        {'name': 'dry martini',
                        'price': 124,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 16}, 'ing2': {'name': 'dry vermouth', 'amount': 4}}},
                        {'name': 'green demon',
                        'price': 127,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 5},
                                            'ing2': {'name': 'vodka', 'amount': 5},
                                            'ing3': {'name': 'pineapple juice', 'amount': 8},
                                            'ing4': {'name': 'blue curaçao', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 2}}},
                        {'name': 'espresso martini',
                        'price': 129,
                        'makingprocess': {'ing1': {'name': 'vodka', 'amount': 9},
                                            'ing2': {'name': 'kahlúa', 'amount': 8},
                                            'ing3': {'name': 'cream', 'amount': 3}}},
                        {'name': 'blue margarita',
                        'price': 134,
                        'makingprocess': {'ing1': {'name': 'tequila', 'amount': 10},
                                            'ing2': {'name': 'blue curaçao', 'amount': 4},
                                            'ing3': {'name': 'lime juice', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'midori sour',
                        'price': 178,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 9},
                                            'ing2': {'name': 'lemon juice', 'amount': 6},
                                            'ing3': {'name': 'sugar syrup', 'amount': 3},
                                            'ing4': {'name': 'egg white', 'amount': 1},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'hugo spritz',
                        'price': 178,
                        'makingprocess': {'ing1': {'name': 'elderflower liqueur', 'amount': 4},
                                            'ing2': {'name': 'prosecco', 'amount': 10},
                                            'ing3': {'name': 'soda water', 'amount': 3},
                                            'ing4': {'name': 'mint', 'amount': 2},
                                            'ing5': {'name': 'ice', 'amount': 1}}},
                        {'name': 'japanese slipper',
                        'price': 192,
                        'makingprocess': {'ing1': {'name': 'midori', 'amount': 8},
                                            'ing2': {'name': 'triple sec', 'amount': 8},
                                            'ing3': {'name': 'lemon juice', 'amount': 4}}},
                        {'name': 'bellini prosecco',
                        'price': 204,
                        'makingprocess': {'ing1': {'name': 'prosecco', 'amount': 14}, 'ing2': {'name': 'peach juice', 'amount': 6}}},
                        {'name': 'peach bellini royale',
                        'price': 206,
                        'makingprocess': {'ing1': {'name': 'peach schnapps', 'amount': 4},
                                            'ing2': {'name': 'peach juice', 'amount': 6},
                                            'ing3': {'name': 'prosecco', 'amount': 10}}},
                        {'name': 'negroni',
                        'price': 228,
                        'makingprocess': {'ing1': {'name': 'gin', 'amount': 7},
                                            'ing2': {'name': 'campari', 'amount': 7},
                                            'ing3': {'name': 'sweet vermouth', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'americano',
                        'price': 234,
                        'makingprocess': {'ing1': {'name': 'campari', 'amount': 7},
                                            'ing2': {'name': 'sweet vermouth', 'amount': 7},
                                            'ing3': {'name': 'soda water', 'amount': 5},
                                            'ing4': {'name': 'ice', 'amount': 1}}},
                        {'name': 'manhattan',
                        'price': 238,
                        'makingprocess': {'ing1': {'name': 'whiskey', 'amount': 12},
                                            'ing2': {'name': 'sweet vermouth', 'amount': 6},
                                            'ing3': {'name': 'bitters', 'amount': 2}}}
]

drink_bar_library = {
                            "vodka": ingredient_icons_list[0],
                            "gin": ingredient_icons_list[40],
                            "orange juice": ingredient_icons_list[20],
                            "white rum": ingredient_icons_list[1],
                            "cola": ingredient_icons_list[3],
                            "tonic water": ingredient_icons_list[33],
                            "soda water": ingredient_icons_list[34],
                            "lime juice": ingredient_icons_list[23],
                            "mint": ingredient_icons_list[38],
                            "sugar syrup": ingredient_icons_list[30],
                            "ice": ingredient_icons_list[37],
                            "dark rum": ingredient_icons_list[2],
                            "tequila": ingredient_icons_list[5],
                            "whiskey": ingredient_icons_list[41],
                            "triple sec": ingredient_icons_list[6],
                            "amaretto": ingredient_icons_list[7],
                            "kahlúa": ingredient_icons_list[8],
                            "baileys": ingredient_icons_list[10],
                            "champagne": ingredient_icons_list[4],
                            "prosecco": ingredient_icons_list[11],
                            "peach schnapps": ingredient_icons_list[12],
                            "blue curaçao": ingredient_icons_list[13],
                            "midori": ingredient_icons_list[14],
                            "absinthe": ingredient_icons_list[15],
                            "dry vermouth": ingredient_icons_list[17],
                            "sweet vermouth": ingredient_icons_list[16],
                            "campari": ingredient_icons_list[18],
                            "elderflower liqueur": ingredient_icons_list[9],
                            "pineapple juice": ingredient_icons_list[21],
                            "cranberry juice": ingredient_icons_list[22],
                            "lemon juice": ingredient_icons_list[24],
                            "grapefruit juice": ingredient_icons_list[25],
                            "apple juice": ingredient_icons_list[26],
                            "mango juice": ingredient_icons_list[28],
                            "passionfruit juice": ingredient_icons_list[19],
                            "peach juice": ingredient_icons_list[27],
                            "grenadine": ingredient_icons_list[31],
                            "coconut cream": ingredient_icons_list[32],
                            "ginger beer": ingredient_icons_list[36],
                            "egg white": ingredient_icons_list[35],
                            "cream": ingredient_icons_list[42],
                            "lime": ingredient_icons_list[29],
                            "bitters": ingredient_icons_list[39]
                        }

glass_tags_bar_library = {
                            1: glass_tags_list[0],
                            2: glass_tags_list[1],
                            3: glass_tags_list[2],
                            4: glass_tags_list[3],
                            5: glass_tags_list[4],
                            6: glass_tags_list[5],
                            7: glass_tags_list[6],
                            8: glass_tags_list[7],
                            9: glass_tags_list[8],
                            10: glass_tags_list[9],
                            11: glass_tags_list[10],
                            12: glass_tags_list[11],
                            13: glass_tags_list[12],
                            14: glass_tags_list[13],
                            15: glass_tags_list[14],
                            16: glass_tags_list[15],
                            17: glass_tags_list[16],
                            18: glass_tags_list[17],
                            19: glass_tags_list[18],
                            20: glass_tags_list[19],
                            21: glass_tags_list[20],
                            22: glass_tags_list[21],
                            23: glass_tags_list[22],
                            24: glass_tags_list[23],
                            25: glass_tags_list[24],
                            26: glass_tags_list[25],
                            27: glass_tags_list[26],
                            28: glass_tags_list[27],
                            29: glass_tags_list[28],
                            30: glass_tags_list[29],
                            31: glass_tags_list[30],
                            32: glass_tags_list[31],
                            33: glass_tags_list[32],
                            34: glass_tags_list[33],
                            35: glass_tags_list[34],
                            36: glass_tags_list[35],
                        }

glasses_bar_library = {
                            "1.1": glasses_list[0],
                            "1.2": glasses_list[1],
                            "1.3": glasses_list[2],
                            "2.1": glasses_list[3],
                            "2.2": glasses_list[4],
                            "2.3": glasses_list[5],
                            "3.1": glasses_list[6],
                            "3.2": glasses_list[7],
                            "3.3": glasses_list[8],
                            "4.1": glasses_list[9],
                            "4.2": glasses_list[10],
                            "4.3": glasses_list[11],
                            "5.1": glasses_list[12],
                            "5.2": glasses_list[13],
                            "5.3": glasses_list[14],
                            "6.1": glasses_list[15],
                            "6.2": glasses_list[16],
                            "6.3": glasses_list[17],
                            "7.1": glasses_list[18],
                            "7.2": glasses_list[19],
                            "7.3": glasses_list[20],
                            "8.1": glasses_list[21],
                            "8.2": glasses_list[22],
                            "8.3": glasses_list[23],
                            "9.1": glasses_list[24],
                            "9.2": glasses_list[25],
                            "9.3": glasses_list[26],
                            "10.1": glasses_list[27],
                            "10.2": glasses_list[28],
                            "10.3": glasses_list[29],
                            "11.1": glasses_list[30],
                            "11.2": glasses_list[31],
                            "11.3": glasses_list[32],
                            "12.1": glasses_list[33],
                            "12.2": glasses_list[34],
                            "12.3": glasses_list[35],
                            "13.1": glasses_list[36],
                            "13.2": glasses_list[37],
                            "13.3": glasses_list[38],
                            "14.1": glasses_list[39],
                            "14.2": glasses_list[40],
                            "14.3": glasses_list[41],
                            "15.1": glasses_list[42],
                            "15.2": glasses_list[43],
                            "15.3": glasses_list[44],
                            "16.1": glasses_list[45],
                            "16.2": glasses_list[46],
                            "16.3": glasses_list[47],
                            "17.1": glasses_list[48],
                            "17.2": glasses_list[49],
                            "17.3": glasses_list[50],
                            "18.1": glasses_list[51],
                            "18.2": glasses_list[52],
                            "18.3": glasses_list[53],
                            "19.1": glasses_list[54],
                            "19.2": glasses_list[55],
                            "19.3": glasses_list[56],
                            "20.1": glasses_list[57],
                            "20.2": glasses_list[58],
                            "20.3": glasses_list[59],
                            "21.1": glasses_list[60],
                            "21.2": glasses_list[61],
                            "21.3": glasses_list[62],
                            "22.1": glasses_list[63],
                            "22.2": glasses_list[64],
                            "22.3": glasses_list[65],
                            "23.1": glasses_list[66],
                            "23.2": glasses_list[67],
                            "23.3": glasses_list[68],
                            "24.1": glasses_list[69],
                            "24.2": glasses_list[70],
                            "24.3": glasses_list[71],
                            "25.1": glasses_list[72],
                            "25.2": glasses_list[73],
                            "25.3": glasses_list[74],
                            "26.1": glasses_list[75],
                            "26.2": glasses_list[76],
                            "26.3": glasses_list[77],
                            "27.1": glasses_list[78],
                            "27.2": glasses_list[79],
                            "27.3": glasses_list[80]
                        }

ingredient_color_library = {
        # spirits
        "white rum":            (195, 230, 220),
        "dark rum":             (101, 55,  20),
        "gin":                  (180, 220, 235),
        "vodka":                (160, 200, 230),
        "tequila":              (195, 210, 130),
        "whiskey":              (180, 100, 30),
        "triple sec":           (255, 200, 50),
        "amaretto":             (160, 60,  10),
        "kahlúa":               (45,  20,  5),
        "baileys":              (210, 165, 90),
        "champagne":            (220, 195, 60),
        "prosecco":             (210, 185, 55),
        "peach schnapps":       (255, 160, 60),
        "blue curaçao":         (0,   120, 210),
        "midori":               (40,  200, 60),
        "absinthe":             (60,  150, 40),
        "dry vermouth":         (190, 195, 80),
        "sweet vermouth":       (160, 45,  20),
        "campari":              (200, 30,  20),
        "elderflower liqueur":  (190, 210, 80),

        # juices
        "orange juice":         (240, 130, 20),
        "pineapple juice":      (225, 195, 20),
        "cranberry juice":      (170, 10,  40),
        "lime juice":           (100, 185, 30),
        "lemon juice":          (220, 200, 20),
        "grapefruit juice":     (230, 100, 50),
        "apple juice":          (150, 190, 40),
        "mango juice":          (245, 140, 10),
        "passionfruit juice":  (232, 175, 16),
        "peach juice":          (230, 130, 50),

        # syrups & sweet
        "sugar syrup":          (180, 210, 140),
        "grenadine":            (190,  10,  40),
        "coconut cream":        (242, 230, 196),

        # sodas
        "cola":                 (45,   20,   5),
        "tonic water":          (224, 242, 220),
        "ginger beer":          (195, 160,  60),
        "soda water":           (225, 247, 242),

        # other
        "egg white":            (200, 210, 160),
        "cream":                (210, 185, 100),
        "lime":                 (80,  165, 30),
        "mint":                 (30,  140, 40),
        "bitters":              (110, 40,  15),
    }

unlocked_ingredients = [
        {"name": "vodka", "price": 5, "owned": 0},
        {"name": "gin", "price": 5, "owned": 0},
        {"name": "orange juice", "price": 2, "owned": 0},
        {"name": "white rum", "price": 5, "owned": 0},
        {"name": "cola", "price": 2, "owned": 0},
        {"name": "tonic water", "price": 2, "owned": 0},
        {"name": "soda water", "price": 1, "owned": 0},
        {"name": "lime juice", "price": 2, "owned": 0},
        {"name": "mint", "price": 1, "owned": 0},
        {"name": "sugar syrup", "price": 1, "owned": 0},
        {"name": "ice", "price": 1, "owned": 0}]